<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title inertia>{{ config('app.name', 'slot4u') }}</title>

    {{-- Brand icons (SLO-170). Static paths under public/, generated by
         `php artisan brand:icons` from resources/images/brand-tile.svg.
         No .ico: every browser slot4u supports takes a PNG favicon, and an .ico
         would be a second format to keep in step for the sake of IE. --}}
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-touch-icon.png">
    {{-- Apply the saved theme before first paint (dark default) to avoid a flash.
         Nonce-carrying: the CSP (SLO-145) allows no inline script without one. --}}
    <script nonce="{{ Illuminate\Support\Facades\Vite::cspNonce() }}">
        (function () {
            try {
                var t = localStorage.getItem('theme') || 'dark';
                document.documentElement.classList.toggle('dark', t !== 'light');
            } catch (e) {}
        })();
    </script>
    @include('partials.analytics')
    @viteReactRefresh
    @vite(['resources/js/app.tsx'])
    @inertiaHead
</head>
<body class="min-h-screen bg-background text-foreground antialiased">
    @inertia
</body>
</html>
