<?php

namespace App\Actions\Quote;

use App\Actions\Booking\ChangeBookingStatus;
use App\Enums\QuoteRequestStatus;
use App\Events\QuoteRequestStatusChanged;
use App\Exceptions\InvalidQuoteTransitionException;
use App\Models\QuoteRequest;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

/**
 * Moves a quote request to a new status through the shared state machine
 * (docs/04 §6, SLO-27): rejects an illegal transition and fires the domain event
 * M5 listeners hook into. This is the ONLY sanctioned way to change a quote
 * request's status; the higher-level actions ({@see SubmitQuote},
 * {@see AcceptQuoteRequest}, {@see RejectQuoteRequest}) route through it after
 * writing their own side effects.
 *
 * The transition runs behind a row lock with a re-read (mirroring
 * {@see ChangeBookingStatus}): two concurrent decisions on
 * one request (e.g. a double-clicked accept) serialise, and the second aborts
 * instead of duplicating the work its transaction would otherwise commit — for
 * accept, that means no orphaned booking.
 *
 * @throws InvalidQuoteTransitionException
 */
class ChangeQuoteRequestStatus
{
    public function __invoke(QuoteRequest $quoteRequest, QuoteRequestStatus $to, ?User $actor = null): QuoteRequest
    {
        $from = $quoteRequest->status;

        if (! $from->canTransitionTo($to)) {
            throw new InvalidQuoteTransitionException($from, $to);
        }

        $actor ??= Auth::user();

        return DB::transaction(function () use ($quoteRequest, $from, $to, $actor): QuoteRequest {
            // Re-read under a lock and bail if the status already moved, so a
            // concurrent writer can't be clobbered (and, for accept, a second
            // booking can't be generated by a racing transaction).
            $locked = QuoteRequest::query()->whereKey($quoteRequest->getKey())->lockForUpdate()->first();
            if ($locked !== null && $locked->status !== $from) {
                throw new InvalidQuoteTransitionException($locked->status, $to);
            }

            // status is guarded (not fillable) — set from the action.
            $quoteRequest->status = $to;
            $quoteRequest->save();

            QuoteRequestStatusChanged::dispatch($quoteRequest, $from, $to, $actor);

            return $quoteRequest;
        });
    }
}
